### ISSUE TITLE
Skip new-site prompt for text pastes into text boxes

### ISSUE THREAD

**Issue by gakselrod** [GooglyBlox/ClipboardToFileInput#14]
![image](https://github.com/GooglyBlox/ClipboardToFileInput/assets/1813727/a4bfd99c-b02c-4b18-a24e-a571c1c17872)

When I'm on a website and ctrl+v for the first time, the extension asks this prompt. Since I'm almost always ctrl+v'ing text into a textbox, there's little to no chance I'd ever hit OK here. Suggestion: if the cursor is in a text box and my clipboard is not a binary blob like an image, skip showing this prompt. Still show it the first time that^ condition doesn't match.

**Comment by GooglyBlox** [comment]
I thought I'd tackle this one quickly before working on #13! The condition I'm currently using is:
User is in a text input or textarea | Skip prompt, do not paste

This will be the case regardless of whether or not you have text in your clipboard, since it'd probably be pretty annoying if you were to try pasting an image into a text field and it kept trying to prompt a file upload! Below is a v2.9.2 RC, would love it if you could test it to make sure it works for your purposes before I push it out with the next update! I'll work on #13 shortly too, and it'll also have this issue's fix.

https://www.mediafire.com/file/cekz89ljnij73kb/ClipboardToFileInput.zip/file

**Comment by gakselrod** [comment]
Works perfectly!

**Comment by GooglyBlox** [comment]
Perfect! I'll close this issue then, glad to see it working.
