### ISSUE TITLE
Roll20 Library Upload

### ISSUE THREAD

**Issue by ElCapitanode** [GooglyBlox/ClipboardToFileInput#8]
Miss me? :P 
Cant browse files on r20, it opens a link in another tab thats probably supposed to open my explorer but it doesnt work.

**Comment by GooglyBlox** [comment]
Alrighty, round two! 😆 

What's the exact URL that you're facing the issue at? Scrolling through r20 and can't find an input field to test on.

**Comment by ElCapitanode** [comment]
The Upload Files button in the library of my campaign. You might need to create a campaign to use it
![image](https://github.com/GooglyBlox/ClipboardToFileInput/assets/160644754/421b8dba-2806-43f4-b921-c7f9899b2e25)

**Comment by GooglyBlox** [comment]
Another situation where it seems to be working fine for me but not for you 😓 
https://github.com/GooglyBlox/ClipboardToFileInput/assets/53668973/43333908-4aef-4c88-a42c-96eb9ecaa9c0
Edit: I realized I clipped the wrong image being dragged onto the editor, but you can see the correct one also pop up on the right side afterward!

Maybe I unintentionally fixed it while working on version 2.6 - since last time uploading the zip straight to GitHub gave you a 404, could you download the 2.6 beta from here? https://www.mediafire.com/file/sn08hrq0lhqxecg/ClipboardToFileInput.zip/file

Hopefully it'll work! If not, let's do what we did last time, and if you could send a picture of the console logs + a video of you replicating the issue.

**Comment by ElCapitanode** [comment]
Yep, works with the 2.6!

**Comment by GooglyBlox** [comment]
What a relief! I'll push out the final 2.6 release tomorrow morning and close this issue, glad this one was basically pre-resolved 😄
